const prompt = require("prompt-sync")({sigint: true});
const number= (parseIntprompt('Enter a  number between 1 to 7'));
if(number==1)
    console.log("MONDAY")
else if(number==2)
    console.log("TUESDAY")
else if(number==3)
    console.log("WEDNESDAY")
if(number==4)
    console.log("THURSDAY")
else if(number==5)
    console.log("FRIDAY")
else if(number==6)
    console.log("SATURDAY")
else (number==7)
    console.log("SUNDAY")
